---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  dpi = 350
)
```

# themeuu `r emo::ji("bird")``r emo::ji("painting")`

<!-- badges: start -->
<!-- badges: end -->

The goal of `themeuu` is to provide a easy style guide that adheres to [Ulster University's branding criteria](https://www.ulster.ac.uk/__data/assets/pdf_file/0008/391058/UU-Brand-Guidelines-April-2019.pdf). 

## Installation

`themeuu` can be installed from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Scott-S-Hannah/themeuu")
```
## Example

`themeuu` possesses several colour scales that adhere to [Ulster University's style guide](https://www.ulster.ac.uk/__data/assets/pdf_file/0008/391058/UU-Brand-Guidelines-April-2019.pdf). 

```{r example}
library(themeuu)
## basic example code
themeuu::ulster_palettes

```

here are some examples if the two main colour schemes:

```{r plots, echo = FALSE}
library(ggplot2)
ggplot(iris, aes(x = Sepal.Width, Sepal.Length, colour = Species)) +
  geom_point(size = 2) +
  scale_color_ulster(discrete = TRUE, palette = "main_1") +
  theme_light() +
  labs(title = "main_1 colour scheme")

ggplot(iris, aes(x = Sepal.Width, Sepal.Length, colour = Species)) +
  geom_point(size = 2) +
  scale_color_ulster(discrete = TRUE, palette = "main_2") +
  theme_light() +
  labs(title = "main_2 colour scheme")

ggplot(iris, aes(x = Sepal.Width, Sepal.Length, colour = Species)) +
  geom_point(size = 2) +
  scale_color_ulster(discrete = TRUE, palette = "mixed") +
  theme_light() +
  labs(title = "mixed colour scheme")

ggplot(iris, aes(x = Sepal.Width, Sepal.Length, colour = Species)) +
  geom_point(size = 2) +
  scale_color_ulster(discrete = TRUE, palette = "cool") +
  theme_light() +
  labs(title = "cool colour scheme")

ggplot(iris, aes(x = Sepal.Width, Sepal.Length, colour = Species)) +
  geom_point(size = 2) +
  scale_color_ulster(discrete = TRUE, palette = "hot") +
  theme_light() +
  labs(title = "hot colour scheme")
```
